# Â© 2016 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html

ubuntu:
  build: ./dockerfiles/ubuntu
  volumes:
    - ./src:/src
    - ./dist:/dist
    - ./tmp/.ccache:/home/build/.ccache

fedora:
  build: ./dockerfiles/fedora
  volumes:
    - ./src:/src
    - ./dist:/dist
    - ./tmp/.ccache:/home/build/.ccache

ubuntu32:
  build: ./dockerfiles/ubuntu32
  volumes:
    - ./src:/src
    - ./dist:/dist
    - ./tmp/.ccache:/home/build/.ccache

ubuntuclang:
  build: ./dockerfiles/ubuntuclang
  volumes:
    - ./src:/src
    - ./dist:/dist
    - ./tmp/.ccache:/home/build/.ccache

gcc:
  build: ./dockerfiles/gcc
  volumes:
    - ./src:/src
    - ./dist:/dist
    - ./tmp/.ccache:/home/build/.ccache

# Local Variables:
# compile-command: "docker-compose build"
# End:
